### ISSUE TITLE
Error while installing addon mopidy

### ISSUE THREAD

**Issue by FaserF** [kentloving/hassio-addons#1]
`404 Client Error: Not Found ("pull access denied for kloving/mopidy-aarch64, repository does not exist or may require 'docker login': denied: requested access to the resource is denied")`

**Comment by telegreen** [comment]
Confirm this error. The same is for my instance HASSIO on Rpi3B.

Core
Version
core-2021.2.3

Supervisor
Version
supervisor-2021.02.9

Operating System
Home Assistant OS 5.11

**Comment by zepfietje** [comment]
I'm also running into this.

**Comment by r0667002** [comment]
Same for me. Too bad because I was loving this add-on on my previous instance. Any fix coming up @kentloving ?

**Comment by kentloving** [comment]
Well, I can understand the reason for @FaserF 's issue - there is only a docker image for armv7.
Question for @zepfietje , @r0667002 , and @telegreen : do you get the same as @FaserF ? That is, do you get the error "access denied for kloving/mopidy-aarch64" ?

**Comment by r0667002** [comment]
Yes, same error for me! So I guess a 32 bit version of HAssos is required for this add-on to run?

**Comment by kentloving** [comment]
Yes, I only a 32 bit version because I run on a Raspberry Pi 3B. I didn't know they've release 64 bit Hassos.

What hardware are you using? Raspberry Pi model 4?

**Comment by kentloving** [comment]
I will do an aarch64 build if you you folks will test it.

**Comment by r0667002** [comment]
> I will do an aarch64 build if you you folks will test it.

That would be awesome! Yes sure. Working with VLC now, but it's not nearly as good.

**Comment by zepfietje** [comment]
I'm also running the 64-bit version of Home Assistant.
Would be awesome if you could release a build for us!

**Comment by kentloving** [comment]
Well, sad news... the Mopidy developers did not release an aarch64 version of Mopidy. I don't have the skills to make one, so I can't build an aarch64 release of this add-on. See also https://docs.mopidy.com/en/latest/installation/debian/

Maybe if someone can motivate the Mopidy developers to make an aarch64 release, then we can try this again.

**Comment by FaserF** [comment]
Thanks anyway for trying. :) 
I will close the issue then.
